In [1]:
import numpy as np

## 基本概念
- list ndarray的互换
- 简单的四则运算
- 数据类型
- 形状维度

In [3]:
array = [1, 2, 3, 4, 5]
type(array)

list

In [4]:
array = np.array(array) # list 转换 ndarray
type(array)

numpy.ndarray

In [5]:
array += 1
array

array([2, 3, 4, 5, 6])

In [7]:
arr1 = array
arr2 = array - 1
# element-wise caculate
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[ 3  5  7  9 11]
[1 1 1 1 1]
[ 2  6 12 20 30]
[2.         1.5        1.33333333 1.25       1.2       ]


In [10]:
py_list = array # ndarray 与 list可以直接互换
print(py_list)
print(type(py_list))

[2 3 4 5 6]
<class 'numpy.ndarray'>


In [11]:
arr1 = np.array([1 , 2, 3, 4, 5])
arr1.dtype

dtype('int32')

In [13]:
arr1 = np.array([1 , 2, 3, 4, 5.0])
arr1.dtype

dtype('float64')

In [14]:
arr1 = np.array([1 , 2, 3, 4, '5.0'])
arr1.dtype
# U11字符串编码形式

dtype('<U11')

In [15]:
print(arr1) #可以看出全部转换成了字符串类型,即ndarray必须是同一种数据类型，若不一样会自动转换

['1' '2' '3' '4' '5.0']


In [98]:
arr1 = np.arange(10)
print(arr1.dtype)
arr1 =  np.asarray(arr1 , np.float)
print(arr1.dtype)

int32
float64


In [103]:
arr1 = np.array([1,2,'3',7.5,'ak47'], dtype=object)
print(arr1.dtype)
print(arr1 * 2)

object
[2 4 '33' 15.0 'ak47ak47']


In [16]:
arr1.itemsize #每个元素的字节数

44

In [17]:
arr1.shape # 数组的形状
# np.shape(arr1)

(5,)

In [18]:
arr1.ndim

1

In [20]:
arr1 = np.array([[1 , 2, 3, 4, 5.0]])
arr1.shape

(1, 5)

## 索引与切片
- 与list基本相同

In [23]:
arr = np.array([1 , 2, 3, 4, 5.0])
arr[-1]

5.0

In [24]:
arr[:-1]

array([1., 2., 3., 4.])

In [25]:
arr[:]

array([1., 2., 3., 4., 5.])

In [26]:
arr[::]

array([1., 2., 3., 4., 5.])

In [30]:
arr[0:5:1]

array([1., 2., 3., 4., 5.])

In [44]:
li = [1,2,3,4,5]
li.reverse()
print(li)

[5, 4, 3, 2, 1]


In [95]:
arr[::-1]

array([50, 40, 30, 20, 10,  0])

## 矩阵
- 形状
- *与dot的区别
- 取某行某列 索引
- 深浅拷贝
- 随机数
- where

In [54]:
arr = np.array([[1,2,3],
               [2,3,4],
               [4,5,6]])
arr

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [55]:
arr.shape

(3, 3)

In [56]:
arr.ndim

2

In [57]:
arr1 = np.array([[0,0,0],
                 [0,0,0],
                 [1,1,1]
                ])
arr*arr1 # *操作是elem-wise

array([[0, 0, 0],
       [0, 0, 0],
       [4, 5, 6]])

In [59]:
arr[0] #第0行 实际上是取出第一个维度下的第一个张量

array([1, 2, 3])

In [77]:
#取一列 
tmp = np.arange(arr.shape[1]) #构建等差数组
print(tmp)
for idx,vec in enumerate(arr): #enumerate索引遍历
    tmp[idx] = vec[0]
    #print(vec[0])
tmp

[0 1 2]


array([1, 2, 4])

In [67]:
arr[-1][0]

4

In [78]:
arr2 = arr
arr2[0][0] = 100
arr2


array([[100,   2,   3],
       [  2,   3,   4],
       [  4,   5,   6]])

In [79]:
arr #引用式的赋值，指向同一块内存

array([[100,   2,   3],
       [  2,   3,   4],
       [  4,   5,   6]])

In [81]:
arr3=arr.copy()
arr3[0][0] = 1
arr3

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [82]:
arr

array([[100,   2,   3],
       [  2,   3,   4],
       [  4,   5,   6]])

In [83]:
# 掩码操作
mask = np.array([0,0,0,1,1,1], dtype=bool)
mask

array([False, False, False,  True,  True,  True])

In [86]:
arr = np.arange(0,60,10)
arr[mask]

array([30, 40, 50])

In [91]:
m = arr > 30
m

array([False, False, False, False,  True,  True])

In [94]:
np.where(arr > 30) #where找出符合条件的元素的位置
arr[np.where(arr > 30)]

array([40, 50])

In [90]:
# 随机数
ra = np.random.rand(10,2)
ra

array([[0.56373004, 0.68010426],
       [0.07627948, 0.74256835],
       [0.96566521, 0.28121884],
       [0.0803513 , 0.48535704],
       [0.01553762, 0.99108283],
       [0.95184153, 0.91766749],
       [0.08192986, 0.03537895],
       [0.92510452, 0.59705626],
       [0.36309718, 0.05141895],
       [0.86227393, 0.36769124]])

## 数值计算
- 

In [118]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [119]:
np.sum(arr)

21

In [120]:
arr = np.random.randint(0,10,(3,3))
arr

array([[4, 9, 4],
       [7, 4, 0],
       [4, 0, 3]])

In [121]:
#指定轴求和 
print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))  

[15 13  7]
[17 11  7]


In [125]:
# 高维数组 维度元组(x1,x2,..,xn)xi代表从外向内第i个中括号内的元素个数
arr = np.random.randint(0,10,(3,3,2))
arr

array([[[4, 8],
        [4, 0],
        [0, 7]],

       [[0, 4],
        [9, 6],
        [7, 5]],

       [[7, 6],
        [9, 4],
        [9, 0]]])

In [126]:
#指定轴求和 
print(np.sum(arr, axis=0)) #结果shape是和第0维内任意一个元素维度相同，3X2
print('*'*80)
print(np.sum(arr, axis=1)) 
print('*'*80)
print(np.sum(arr, axis=2))

[[11 18]
 [22 10]
 [16 12]]
********************************************************************************
[[ 8 15]
 [16 15]
 [25 10]]
********************************************************************************
[[12  4  7]
 [ 4 15 12]
 [13 13  9]]


### 对numpy维度的一些理解
- 形如[1,2,3]这样的东西看似是个数学中的向量，但在numpy眼中只是3个数按照一个维度排列起来。故而numpy不考虑行向量还是列向量，反正它就是一个一维数组
- 按照某一维度做消融操作时，相当于将这一维度按给定操作压扁，其他维度不变

In [128]:
print(arr)
arr.prod(axis=0) #按给定轴求积

[[[4 8]
  [4 0]
  [0 7]]

 [[0 4]
  [9 6]
  [7 5]]

 [[7 6]
  [9 4]
  [9 0]]]


array([[  0, 192],
       [324,   0],
       [  0,   0]])

In [129]:
arr.max(axis=0)

array([[7, 8],
       [9, 6],
       [9, 7]])

In [130]:
arr.min(axis=0)

array([[0, 4],
       [4, 0],
       [0, 0]])

In [131]:
arr.argmax(axis=2) #返回沿着该维度的向量最大值在该维度的位置，所以结果shape是除了该维度的其他维度组成

array([[1, 0, 1],
       [1, 0, 0],
       [0, 0, 0]], dtype=int64)

In [134]:
arr = arr.flatten()
print(arr)
arr.argmax() # 不指定维度实际上就是先进性flatten操作

[4 8 4 0 0 7 0 4 9 6 7 5 7 6 9 4 9 0]


8

In [141]:
arr = np.random.randint(0,10,(3,3,2))
print(arr)
print(arr.var(axis=0))

[[[5 0]
  [2 7]
  [9 3]]

 [[6 5]
  [0 5]
  [0 3]]

 [[7 4]
  [2 7]
  [3 9]]]
[[ 0.66666667  4.66666667]
 [ 0.88888889  0.88888889]
 [14.          8.        ]]


In [149]:
arr = np.array([0,1, 0.6, 1.5])
arr.round()

array([0., 1., 1., 2.])

## 排序
- 默认按照axis=-1排序

In [165]:
arr = np.random.randint(1,50,(3,3))
print(arr)
print('*'*100)

arr.sort()
print(arr)
print('*'*100)

arr.sort(axis=0)
print(arr)
print('*'*100)

arr = arr.argsort(axis=0)
print(arr)
print('*'*100)

[[34 33 31]
 [ 1 18 21]
 [33 11 11]]
****************************************************************************************************
[[31 33 34]
 [ 1 18 21]
 [11 11 33]]
****************************************************************************************************
[[ 1 11 21]
 [11 18 33]
 [31 33 34]]
****************************************************************************************************
[[0 0 0]
 [1 1 1]
 [2 2 2]]
****************************************************************************************************


In [168]:
arr = np.linspace(0,10,10) #0到10之间插入总共10个数，间隔均匀
arr

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [169]:
v = np.array([2.3,5.6,7.99])
np.searchsorted(arr, v) #Find indices where elements should be inserted to maintain order. 不改变a数组

array([3, 6, 8], dtype=int64)

In [170]:
arr

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

### 多维数组索引

In [172]:
arr = np.array([[1,0,6],
              [1,7,0],
              [2,3,1],
              [2,4,0]])
arr

array([[1, 0, 6],
       [1, 7, 0],
       [2, 3, 1],
       [2, 4, 0]])

In [178]:
print(arr[:,0]) #取出第0列
print(arr[:1]) #切片，维度不变
print(arr[:1].shape) 
print(arr[0]) #取出第0个元素

[1 1 2 2]
[[1 0 6]]
(1, 3)
[1 0 6]


In [174]:
arr[0,:] #取出第0行

array([1, 0, 6])

In [182]:
print(arr[0,0])#
print(arr[0][0])

1
1


In [190]:
#arr[ , ]和arr[][]同样
print(arr[0][::]) 
print(type(arr[0][::]))
print(arr[0])
print(type(arr[0]))
print(arr[0,:])
print(type(arr[0,:]))

[1 0 6]
<class 'numpy.ndarray'>
[1 0 6]
<class 'numpy.ndarray'>
[1 0 6]
<class 'numpy.ndarray'>


In [192]:
idx = np.lexsort([-1*arr[:,0] , arr[:,2]]) #order 先按照第2列升序 再按照第0列降序
idx #返回的索引数组说明了排序后的数组是采取了原数组中哪些位置的元素

array([3, 1, 2, 0], dtype=int64)

In [193]:
arr[idx]

array([[2, 4, 0],
       [1, 7, 0],
       [2, 3, 1],
       [1, 0, 6]])

## 形状操作

In [196]:
arr = np.arange(0,20,2)
arr.shape

(10,)

In [197]:
arr.shape = (2,5) #数组shape可以改变

In [198]:
arr

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [208]:
arr = arr.reshape((5,-1))
print(arr)
#arr.reshape((3,-1))#ValueError: cannot reshape array of size 10 into shape (3,newaxis)

[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]]


In [213]:
arr = np.arange(0,20,2)
arr = arr[:, np.newaxis]
print(arr.shape)
print(arr)

(10, 1)
[[ 0]
 [ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]
 [12]
 [14]
 [16]
 [18]]


In [224]:
arr = np.arange(0,20,2)
arr = arr[np.newaxis, :]
print(arr.shape)
print(arr)

(1, 10)
[[ 0  2  4  6  8 10 12 14 16 18]]


In [225]:
arr = arr.squeeze() #去除shape=1的空轴
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [226]:
#数组转置
arr.shape = (2,5)
print(arr)
arr = arr.transpose()
print(arr)
arr = arr.T
print(arr)


[[ 0  2  4  6  8]
 [10 12 14 16 18]]
[[ 0 10]
 [ 2 12]
 [ 4 14]
 [ 6 16]
 [ 8 18]]
[[ 0  2  4  6  8]
 [10 12 14 16 18]]


In [227]:
arr = np.arange(0,24)
# N W H C -> N H W C
arr.shape = (1,4,2, 3)
print(arr)

arr = arr.transpose([0,2,1,3])
print(arr)
print(arr.shape)

[[[[ 0  1  2]
   [ 3  4  5]]

  [[ 6  7  8]
   [ 9 10 11]]

  [[12 13 14]
   [15 16 17]]

  [[18 19 20]
   [21 22 23]]]]
[[[[ 0  1  2]
   [ 6  7  8]
   [12 13 14]
   [18 19 20]]

  [[ 3  4  5]
   [ 9 10 11]
   [15 16 17]
   [21 22 23]]]]
(1, 2, 4, 3)


### 数组连接

In [240]:
arr1 = np.array([[1, 2, 3],[1, 2, 3]])
arr2 = np.array([[9, 9,9],[1, 1, 1]])
arr3 = np.concatenate((arr1 , arr2))#默认 axis=0
arr3

array([[1, 2, 3],
       [1, 2, 3],
       [9, 9, 9],
       [1, 1, 1]])

In [241]:
arr3 = np.concatenate((arr1 , arr2 ), axis=1)
arr3

array([[1, 2, 3, 9, 9, 9],
       [1, 2, 3, 1, 1, 1]])

In [242]:
np.vstack((arr1, arr2))

array([[1, 2, 3],
       [1, 2, 3],
       [9, 9, 9],
       [1, 1, 1]])

In [243]:
np.hstack((arr1, arr2))

array([[1, 2, 3, 9, 9, 9],
       [1, 2, 3, 1, 1, 1]])

In [244]:
arr1.flatten()

array([1, 2, 3, 1, 2, 3])

In [245]:
arr1

array([[1, 2, 3],
       [1, 2, 3]])

In [246]:
 arr1.ravel() #与flatten一样

array([1, 2, 3, 1, 2, 3])

## 数组生成

In [247]:
arr = np.random.randint(1,10,(3,3))
arr

array([[9, 5, 3],
       [7, 4, 6],
       [1, 5, 4]])

In [248]:
arr = np.arange(2, 20, 2, dtype=np.float)
arr

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])